### ISSUE TITLE
TFS/AzureDevOps pull request excluded if no label

### ISSUE THREAD

**Issue by EbenZhang** [jasminsehic/PullRequestReleaseNotes#42]
If the pull request has no label, then it will be excluded from the results. Is there a particular reason?

[this line](https://github.com/jasminsehic/PullRequestReleaseNotes/commit/0f9e7cd4e45adf8c9e9bf25a275da1bcc9388beb#diff-52855b49b955b49632dfe0336ba056f0cf6d3834b12d0519ac47a079f6eea89dR108) specically

**Comment by jasminsehic** [comment]
Just looking at BitBucket provider it has the same issue, possible even others. Sounds like I messed up something to do with `-ExcludeLabel` feature, should only return null from `GetPullRequestDto()` if the exclude label matches. So this issue is valid and needs to be fixed in every provider affected.

**Comment by jasminsehic** [comment]
Fixed in #43
